chore(login): rewrite cockpit login page
camunda/camunda-bpm-webapp pull request #353
Opened 2020-10-20 09:19 UTC by marstamm

related to CAM-12616

2020-10-20 09:20 UTC, marstamm commented on ui/cockpit/package.json
> +    "react-bootstrap": "1.3.0",
Using a UI lib is still up to debate

2020-10-30 13:15 UTC, tasso94 requested changes
Looks good to me. Good job! 

I found two regressions:
* Form does not clear itself after submitting wrong credentials
* Notification "Login failed" previously showed "Process engine with name engine3 does not exist"; this notification does not exist anymore

2020-10-30 13:15 UTC, tasso94 commented on ui/cockpit/src/components/Login/Login.js
> +          onChange={e => setUsername(e.target.value)}
```suggestion
          onChange={e => setUsername(e.target.value)}
          required
```

2020-10-30 13:15 UTC, tasso94 commented on ui/cockpit/src/components/Login/Login.js
> +          onChange={e => setPassword(e.target.value)}
```suggestion
          onChange={e => setPassword(e.target.value)}
          required
```

2020-11-03 07:44 UTC, tasso94 approved these changes
LGTM! 🚀

2020-11-03 07:46 UTC, merged